part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const SPLASH_SCREEN = _Paths.SPLASH_SCREEN;
  static const WELCOME_SCREEN = _Paths.WELCOME_SCREEN;
  static const ONBOARDING_SCREEN = _Paths.ONBOARDING_SCREEN;
  static const SIGN_IN = _Paths.SIGN_IN;
  static const CREATE_ACCOUNT = _Paths.CREATE_ACCOUNT;
  static const OTP_SCREEN = _Paths.OTP_SCREEN;
  static const NEW_PASSWORD_SCREEN = _Paths.NEW_PASSWORD_SCREEN;
  static const PROFILE_INFO_ADD_SCREEN = _Paths.PROFILE_INFO_ADD_SCREEN;
  static const LOCA_ALLOW_PERMI_SCREEN = _Paths.LOCA_ALLOW_PERMI_SCREEN;
  static const ADD_MANU_LOCA_SCREEN = _Paths.ADD_MANU_LOCA_SCREEN;
  static const BOTTOM_NAVIGATION_BAR = _Paths.BOTTOM_NAVIGATION_BAR;
  static const EXPLORE_SCREEN = _Paths.EXPLORE_SCREEN;
  static const BOOKINGS_SCREEN = _Paths.BOOKINGS_SCREEN;
  static const CHAT_SCREEN = _Paths.CHAT_SCREEN;
  static const PROFILE_SCREEN = _Paths.PROFILE_SCREEN;
  static const FAVORITES_SCREEN = _Paths.FAVORITES_SCREEN;
  static const FAVORITES_DOCTORS = _Paths.FAVORITES_DOCTORS;
  static const FAVORITES_HOSPITALS = _Paths.FAVORITES_HOSPITALS;
  static const DOCTOR_DETAILS = _Paths.DOCTOR_DETAILS;
  static const BOOK_APPOINTMENT = _Paths.BOOK_APPOINTMENT;
  static const SELECT_PACKAGE = _Paths.SELECT_PACKAGE;
  static const PATIENT_DETAILS = _Paths.PATIENT_DETAILS;
  static const PAYMENT_METHODS = _Paths.PAYMENT_METHODS;
  static const ADD_CARD = _Paths.ADD_CARD;
  static const REVIEW_SUMMARY = _Paths.REVIEW_SUMMARY;
  static const PAYMENT = _Paths.PAYMENT;
  static const GET_DIRECTION = _Paths.GET_DIRECTION;
  static const LOCATION_DONE = _Paths.LOCATION_DONE;
  static const TOP_SPECIALIST = _Paths.TOP_SPECIALIST;
  static const NEARBY_HOSPITALS = _Paths.NEARBY_HOSPITALS;
  static const HOSPITAL_DETAIL = _Paths.HOSPITAL_DETAIL;
  static const SEARCH_SCREEN = _Paths.SEARCH_SCREEN;
  static const FILTER_SCREEN = _Paths.FILTER_SCREEN;
  static const CANCLE_BOOKING = _Paths.CANCLE_BOOKING;
  static const DOCTOR_REVIEW_SCREEN = _Paths.DOCTOR_REVIEW_SCREEN;
  static const HOSPITAL_REVIEW_SCREEN = _Paths.HOSPITAL_REVIEW_SCREEN;
  static const MY_APPOINTMENT = _Paths.MY_APPOINTMENT;
  static const MESSAGE_SCREEN = _Paths.MESSAGE_SCREEN;
  static const CATEGORY = _Paths.CATEGORY;
  static const NOTIFICATION_SCREEN = _Paths.NOTIFICATION_SCREEN;
  static const VIDEO_CALL_SCREEN = _Paths.VIDEO_CALL_SCREEN;
  static const CONSULTATION_SCREEN = _Paths.CONSULTATION_SCREEN;
  static const YOUR_PROFILE = _Paths.YOUR_PROFILE;
  static const SETTINGS = _Paths.SETTINGS;
  static const HELP_CENTER = _Paths.HELP_CENTER;
  static const PRIVACY_POLICY = _Paths.PRIVACY_POLICY;
  static const PASSWORD_MANAGER = _Paths.PASSWORD_MANAGER;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const SPLASH_SCREEN = '/splash-screen';
  static const WELCOME_SCREEN = '/welcome-screen';
  static const ONBOARDING_SCREEN = '/onboarding-screen';
  static const SIGN_IN = '/sign-in';
  static const CREATE_ACCOUNT = '/create-account';
  static const OTP_SCREEN = '/otp-screen';
  static const NEW_PASSWORD_SCREEN = '/new-password-screen';
  static const PROFILE_INFO_ADD_SCREEN = '/profile-info-add-screen';
  static const LOCA_ALLOW_PERMI_SCREEN = '/loca-allow-permi-screen';
  static const ADD_MANU_LOCA_SCREEN = '/add-manu-loca-screen';
  static const BOTTOM_NAVIGATION_BAR = '/bottom-navigation-bar';
  static const EXPLORE_SCREEN = '/explore-screen';
  static const BOOKINGS_SCREEN = '/bookings-screen';
  static const CHAT_SCREEN = '/chat-screen';
  static const PROFILE_SCREEN = '/profile-screen';
  static const FAVORITES_SCREEN = '/favorites-screen';
  static const FAVORITES_DOCTORS = '/favorites-doctors';
  static const FAVORITES_HOSPITALS = '/favorites-hospitals';
  static const DOCTOR_DETAILS = '/doctor-details';
  static const BOOK_APPOINTMENT = '/book-appointment';
  static const SELECT_PACKAGE = '/select-package';
  static const PATIENT_DETAILS = '/patient-details';
  static const PAYMENT_METHODS = '/payment-methods';
  static const ADD_CARD = '/add-card';
  static const REVIEW_SUMMARY = '/review-summary';
  static const PAYMENT = '/payment';
  static const GET_DIRECTION = '/get-direction';
  static const LOCATION_DONE = '/location-done';
  static const TOP_SPECIALIST = '/top-specialist';
  static const NEARBY_HOSPITALS = '/nearby-hospitals';
  static const HOSPITAL_DETAIL = '/hospital-detail';
  static const SEARCH_SCREEN = '/search-screen';
  static const FILTER_SCREEN = '/filter-screen';
  static const CANCLE_BOOKING = '/cancle-booking';
  static const DOCTOR_REVIEW_SCREEN = '/doctor-review-screen';
  static const HOSPITAL_REVIEW_SCREEN = '/hospital-review-screen';
  static const MY_APPOINTMENT = '/my-appointment';
  static const MESSAGE_SCREEN = '/message-screen';
  static const CATEGORY = '/category';
  static const NOTIFICATION_SCREEN = '/notification-screen';
  static const VIDEO_CALL_SCREEN = '/video-call-screen';
  static const CONSULTATION_SCREEN = '/consultation-screen';
  static const YOUR_PROFILE = '/your-profile';
  static const SETTINGS = '/settings';
  static const HELP_CENTER = '/help-center';
  static const PRIVACY_POLICY = '/privacy-policy';
  static const PASSWORD_MANAGER = '/password-manager';
}
